name: Lint files

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1

      - name: Lint shell file
        uses: azohra/shell-linter@v0.5.0
        with:
          path: "entrypoint.sh"

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
